name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - run: |
          echo $TZ
          echo "TZ=Asia/Tokyo" >> $GITHUB_ENV
          echo $TZ
      - run: echo $TZ
      - run: |
          echo "MULTILINE<<EOF" >> $GITHUB_ENV
          echo "line 1" >> $GITHUB_ENV
          echo "line 2" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - run: echo "$MULTILINE"
      - run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://httpbin.org/json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: echo "$JSON_RESPONSE"
      - run: echo "${{ github.workspace }}" >> $GITHUB_PATH
      - run: echo $PATH
