name: hello
on: [push, pull_request]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - use: actions/cache@v1.1.0
        with:
          path: /tmp
          key: cache-${{ github.ref }}-key
          restore-keys: |
            cache-
