name: hello
on: push
env:
  TEST: hoge

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    env:
      TEST: fuga
    steps:
      - run: echo "Hello, World"
      - run: echo $TEST
      - uses: actions/checkout@v1.0.0
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello, World!
      - run: |
          import sys
          print(sys.version)
        shell: python
