name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10, 12]
        include:
          - os: windows-latest
            node: 10
            npm: 6
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ matrix.node }}
      - name: Node.js Version
        run: node -v
      - run: echo ${{ matrix.npm }}
