name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $TZ
          echo "::set-env name=TZ::Asia/Tokyo"
          echo $TZ
      - run: |
          echo $TZ
      - run: |
          echo $HOGE
          TEST="This is line 1
          This is line 2
          This is line 3"
          echo "::set-env name=HOGE::$TEST"
          echo $HOGE
      - run: |
           echo $HOGE
