name: hello
on:
  push:
    branches:
      - "test-refs-branches"

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    env:
      TEST: test
    steps:
      - run: echo "Hello, World"
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
