name: hello
on: push

jobs:
  unit-test:
    container:
      image: node:12.14.1-stretch
      env:
        NODE_ENV: development
      ports:
        - 8080
      volumes:
        - /etc:/hostetc
      options: --privileged --cpus 1 -v "/etc:/hostetc"
    runs-on: windows-latest
    steps:
      - run: echo "Hello, World"
      - run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo $GITHUB_EVENT_PATH
          ls /hostetc
      - run: node -v
      - run: npm -v
      - run: |
          import sys
          print(sys.version)
        shell: python
