name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    container:
      image: node:12.14.1-stretch
      env:
        NODE_ENV: development
      ports:
        - 8080
      options: --cpus 1
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        volumes:
          - /etc:/hostetc
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - run: echo "Hello, World"
      - run: ls /usr/lib
      - run: curl postgres:5432
      - uses: actions/checkout@v1.0.0
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/curl
          args: postgres:5432
      - run: |
          import sys
          print(sys.version)
        shell: python
