name: Node.js Matrix Build
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        node: ['12']
    name: Node ${{ matrix.node }} job on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
      - run: npm i
      - run: npm run eslint
      - run: npm run test:regression
