name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make branch and push it
        run: |
          BRANCH_NAME="merge-$(date +%Y.%m.%d)-${GITHUB_RUN_NUMBER}"
          echo "BRANCH_NAME: ${BRANCH_NAME}"
          git checkout -b ${BRANCH_NAME} origin/main
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "BRANCH_NAME: ${BRANCH_NAME}"
          git push git@github.com:${GITHUB_REPOSITORY}.git ${BRANCH_NAME}
          echo "::set-output name=branch_name:${BRANCH_NAME}"
        id: make-and-push-branch
