name: hello
on: push

jobs:
  build1:
    name: Build1
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "Hello, World"
  build2:
    name: Build2
    runs-on: ubuntu-latest
    needs: [build1]
    if: !failure()
    steps:
      - run: echo "Started"
