name: Checkout
on: push

jobs:
  job1:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World 1"
  job2:
    name: Greeting
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World 2"
  job3:
    name: Greeting
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World 3"
  job4:
    name: Greeting
    needs: [job2, job3]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World 4"
