name: hello
on: push
env:
  TEST: hoge

jobs:
  always-success:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1
  step-always-success:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
