name: hello
on: push

jobs:
  build:
    name: Greeting
    strategy:
      matrix:
        os: [windows-latest, windows-2016, windows-2019, ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macos-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - shell: python
        run: |
          import sys
          print(sys.version)
