name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: self-hosted
    steps:
      - run: echo "Hello, World"
      - run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/miyajan/hello-world-private:latest
