name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.8
      - uses: miyajan/javascript-action-hello
      - run: echo "Hello, World"
      - run: |
          echo "hoge"
          echo "fuga"
