name: hello
on: push

jobs:
  build1:
    name: Build1
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo "Hello, World"
      - run: exit 0
  build2:
    name: Build2
    runs-on: ubuntu-latest
    needs: [build1]
    if: ${{ !failure() && !cancelled() }}
    steps:
      - run: echo "Started"
