name: hello
on: push

jobs:
  build:
    name: Greeting
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04, ubuntu-16.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - shell: python
        run: |
          import sys
          print(sys.version)
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - shell: python
        run: |
          import sys
          print(sys.version)
