name: hello
on: push

jobs:
  test:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - if: success()
        run: echo "success hoge"
      - if: always()
        run: echo "always hoge"
      - if: cancelled()
        run: echo "cancelled hoge"
      - if: failure()
        run: echo "failure hoge"
      - run: echo "${{ 'That''s right' }}"
      - run: echo "${{ toJson(github) }}"
      - run: echo "${{ toJson(env) }}"
      - run: echo "${{ toJson(job) }}"
      - run: echo "${{ toJson(steps) }}"
      - run: echo "${{ toJson(runner) }}"
      - run: echo "${{ toJson(secrets) }}"
      - run: echo "${{ toJson(strategy) }}"
      - run: echo "${{ toJson(matrix) }}"
  build:
    if: github.ref == 'refs/heads/if'
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - uses: actions/checkout@v1.0.0
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello, World!
      - run: |
          import sys
          print(sys.version)
        shell: python
  hoge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "fuga"
