name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ".github/workflows/tag-modules.yaml" > ~/test.txt
          echo "modules/base/budgets.tf" >> ~/test.txt
          cat ~/test.txt | sed -n -e "s/^modules\/\(.*\)\/.*$/\1/p"
