name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: docker://gcr.io/cloud-builders/gcloud
      - run: echo "Hello, World"
      - run: |
          echo "hoge"
          echo "fuga"
