name: hello
on: push

defaults:
  run:
    shell: python
    working-directory: /tmp

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: |
          import os
          print(os.getcwd())
