name: hello
on: push

defaults:
  run:
    shell: python
    working-directory: /tmp

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: /
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: pwd
