name: hello
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir data
          echo "Hello" > data/hello.txt
      - uses: actions/upload-artifact@v2
        with:
          path: data/*
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
      - run: cat data/hello.txt
