name: hello
on: push
env:
  TEST: hoge

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    container:
      image: node:12.14.1-stretch
      env:
        NODE_ENV: development
        TEST: foo
      ports:
        - 8080
      options: --cpus 1
    services:
      nginx:
        image: nginx:1.17.8
        ports:
          - 8080
        options: -v /etc:/hostetc
    steps:
      - run: echo ${TEST}
      - run: echo "${{ job.services.nginx.ports['8080'] }}"
      - run: ls /hostetc
      - uses: actions/checkout@v1.0.0
      - run: |
          import sys
          print(sys.version)
        shell: python
