name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - run: |
          mkdir -p ${{ github.workspace }}/test/hoge
          echo hoge > ${{ github.workspace }}/test/hoge/fuga.txt
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: foo
          path: ${{ github.workspace }}/test/hoge
      - uses: actions/download-artifact@v1.0.0
        with:
          name: foo
