name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ matrix.node }}
      - name: Node.js Version
        run: node -v
