name: hello
on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir data
          echo "data" > data/data.txt
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: data
          path: data.txt
  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - uses: actions/download-artifact@v1.0.0
        with:
          name: data
      - run: cat data/data.txt
