name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - run: actions/checkout@v3
      - run: gh api /repos/:owner/:repo/dispatches --input '{"event_type":"test"}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
