name: hello
on: pull_request

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"
      - if: contains(github.event.pull_request.labels.*.name, 'test')
        run: echo "true"
