name: hello
on: push
env:
  GITHUB_TEST: hoge

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    env:
      GITHUB_TEST: fuga
    steps:
      - run: echo "Hello, World"
      - run: |
          echo $CI
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_NUMBER
      - run: exit 1
      - run: echo $GITHUB_TEST
        env:
          GITHUB_TEST: foo
      - run: echo $GITHUB_REF
      - id: test
        run: echo $GITHUB_HEAD_REF
      - uses: actions/checkout@v1.0.0
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello, World!
      - run: |
          import sys
          print(sys.version)
        shell: python
