name: hello
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miyajan/hello-world-private
      credentials:
        username: ${{ secrets.IMAGE_USERNAME }}
        password: ${{ secrets.IMAGE_PASSWORD }}
    name: Greeting
    steps:
      - run: echo "Hello, World"
  unit-test:
    runs-on: ubuntu-latest
    services:
      private-service:
        image: ghcr.io/miyajan/hello-world-private
        credentials:
          username: ${{ secrets.IMAGE_USERNAME }}
          password: ${{ secrets.IMAGE_PASSWORD }}
    name: hoge
    steps:
      - run: echo "Hello, World"
