name: hello
on: 
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - '!v[0-9]+.[0-9]+.[0-9]+-testing'

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - uses: actions/checkout@v1.0.0
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello, World!
      - run: |
          import sys
          print(sys.version)
        shell: python
