name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    container:
      image: node:12.14.1-stretch
      env:
        NODE_ENV: development
      ports:
        - 8080
      options: --cpus 1
    services:
      nginx:
        image: nginx:1.17.8
        ports:
          - 8080
    steps:
      - run: echo "${{ job.services.nginx.ports['8080'] }}"
      - uses: actions/checkout@v1.0.0
      - run: |
          import sys
          print(sys.version)
        shell: python
