name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10, 12]
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 12
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 12
      - name: Node.js Version
        run: node -v
