name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - id: set-json-output
        run: echo '::set-output name=json::{"greeting":"Hello, World!"}'
      - run: echo ${{ steps.set-json-output.output.greeting }}
