name: hello
on: push

jobs:
  build:
    name: Greeting
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04, ubuntu-16.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - shell: python
        run: |
          import sys
          print("Python {}.{}.{}".format(*sys.version_info))
