name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    container:
      image: node:12.14.1-stretch
      env:
        NODE_ENV: development
      ports:
        - 8080
      options: --cpus 1
    services:
      postgres: postgres:12.1
    steps:
      - run: echo "Hello, World"
      - run: ls /usr/lib
      - run: curl postgres:5432
      - uses: actions/checkout@v1.0.0
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/curl
          args: postgres:5432
      - run: |
          import sys
          print(sys.version)
        shell: python
