name: hello
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - uses: actions/cache@4134e6de47156381d31ff74f8aabf86718858f70
        with:
          path: ~/test
          key: v3-cache-${{ github.ref }}-key
          restore-keys: |
            v3-cache-
      - run: |
          mkdir -p ~/test
          echo "hoge" > ~/test/test.txt
