name: hello
on: push

jobs:
  build:
    name: Greeting
    strategy:
      matrix:
        os: [windows-latest, windows-2016, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - shell: cmd
        run: systeminfo
