name: test
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hoge=fuga" >> $GITHUB_ENV
      - run: echo "${{ env.hoge }}"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.hoge }}"
