name: SSH Debug Test
on: push
jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1.0.2
