name: hello
on: push

jobs:
  unit-test:
    container:
      image: node:12.14.1-stretch
      env:
        NODE_ENV: development
      ports:
        - 8080
      volumes:
        - ./:/usr/src/app
      options: --cpus 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - run: |
          import sys
          print(sys.version)
        shell: python
